### ISSUE TITLE
Main board schematic

### ISSUE THREAD

**Issue by paulsonmathew21** [newaetech/ChipJabber-Unplugged#1]
Hi,

I could not find the main board schematic from this repo. Could you please provide update this repo with the details of main version?

**Comment by colinoflynn** [comment]
As mentioned on the main page - it's still a little TODO as we got way delayed with this. The "simple-pcb" is close to the final main one (a few other changes more related to making the kit out of it). I'm hoping to actually order this before CNY at which point will launch a lot of it off. But for now anything missing is probably not ready for release.
